### ISSUE TITLE
Feature request: proxy configuration/local bootstrap

### ISSUE THREAD

**Issue by hillsy** [lukevenediger/champ#1]
I'm looking at champ for use on a corporate network (precompiled Windows binary is a big win...). Problem is I can't get out through our corporate proxies to download the bootstrap file; champ crashes and gives Unhandled Exception: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

Any possibility of adding a command line flag to specify a local bootstrap file (preferred) or to specify a different proxy?

**Comment by lukevenediger** [comment]
Hi there,

Sure that sounds like a good feature to have! It might take a few days but I'll get to it for sure. Out of interest, can you tell me more about your use case for champ?

Thanks,
Luke

**Comment by hillsy** [comment]
Hi there,

I work in UK public sector, for an organisation that generates reports & data sets for the public. Some of our users need to be able to create static mini-sites for upload onto corporate web servers. Mostly this is things using code auto generated by Google Maps, Fusion, that sort of stuff. Data visualisation experiments etc.

This content doesn't always play well with our corporate CMS, so we want to give them a tool/framework that supports templating (to get the corporate look and feel) and ideally requires nothing special on the server. We've used Dreamweaver templates in the distant past for this sort of thing, but while they work OK, DW is total overkill. Champ seems like it could work, if I could get it to play with - or ignore - our corporate proxies...

cheers

Shaun

**Comment by lukevenediger** [comment]
Hi Shaun,

I've got a gap to look at this feature. Do you need to provide a username/password to your proxy, as well as the address? As a matter of interest, does the box you're running on have your proxy settings configured in the Internet Properties dialog box?

One other way to tackle this is to pass in a location to the --bootstrap argument, telling it where to get the bootstrap file from. Would that work for you?

Thanks,
Luke

**Comment by hillsy** [comment]
The whole "corporate proxy" thing could be a bit of a minefield. I _think_ that's how the system's configured ("Automatically detect settings") and that's controlled by our domain admins, but authenticated or anonymous proxies are also available.

It's your code of course; I'm just making suggestions :) But I'm +1 on passing a (optional?) location to the --bootstrap argument. That gets round the whole problem and maybe adds some additional flexibility.

**Comment by lukevenediger** [comment]
I was worried about how to do authentication, but an anonymous proxy should be pretty straightforward to implement. To be on the safe side, I'll give you the option of using the anonymous proxy or pointing champ at a url or file location to grab the bootstrap template. That way you can try out both and see what fits. WIN!

**Comment by lukevenediger** [comment]
Hi Shaun,

Your feature is available in the latest release. Enjoy!

https://github.com/lukevenediger/champ/releases/tag/v1.1.0.0

Cheers,
Luke
