### ISSUE TITLE
The debug folder and ErrorPageFactory.cs are missing

### ISSUE THREAD

**Issue by endforward** [lukevenediger/champ#2]
I just downloaded the source but I am missing the debug folder containing ErrorPageFactory.cs. It's in the .csproj but the actual files don't seem to be added to the repository.

**Comment by lukevenediger** [comment]
Hi,

Sorry about that, I'll fix this up tonight and let you know.

Cheers,
Luke

**Comment by lukevenediger** [comment]
Hi,

Turns out having my ErrorPageFactory.cs in a folder called 'Debug' caused git to ignore the whole directory. I've renamed 'Debug' to 'DebugHelper' and committed the changes. Please pull again and let me know if it works for you.

Thanks,
Luke
