### ISSUE TITLE
Feature Request : Dynamically generating index page

### ISSUE THREAD

**Issue by imran-a** [lukevenediger/champ#3]
Hello

At the moment when you create a blog entry you need to add a summary and link to index page.

It would be nice if index pages could be dynamically generated by looping the pages/posts in the folder and using the date created as blog post date as default or having a property on the page like you already have for 'template'

I was looking in the code, and perhaps you could introduce a property 'Type' and those index pages could then be type 'list' and passed Model.Pages, everything else could be type 'page' by default.

Would be good to get your thoughts on this. 

In addition if 'list' pages do become a feature, then could it be extended to tags? So each page has an additional property example 'Tags: mvc, grunt' and similar to list pages, something like /tags/mvc.html is also generated?

Really nice tool !

**Comment by lukevenediger** [comment]
Hi Imran,

I've included a feature called lists which sounds like it'll do what you're asking. It's available in the v1.3.0 release: https://github.com/lukevenediger/champ/releases/tag/v1.3.0

And here's an example of how to use it:

https://github.com/lukevenediger/champ-examples/tree/master/simple-list

Hope that helps!
Luke

**Comment by imran-a** [comment]
Hi Luke

Just around to playing with this now ! 

Great stuff, thank you.

Imran

**Comment by lukevenediger** [comment]
Excellent! Let me know how it goes :)
