### ISSUE TITLE
SSL problem with the --boostrap command

### ISSUE THREAD

**Issue by rumplin** [lukevenediger/champ#7]
I'm getting the following error on my Windows 10 machine. I'm not using a proxy.

```
C:\champ>champ.exe --bootstrap
Downloading champ-bootstrap.zip (github.com)

Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at champ.Bootstrap.Run()
   at champ.Program.Main(String[] args)
```

After trying to run the champ.exe again with "-v -b" parameters, I got an windows message "This app can't run on your PC" and ever since, I can't get it to run.

**Comment by chrisfraser** [comment]
This project has not been touched in 6 years. Have you built a lot based on this? If not, maybe consider a more loved templating engine.

**Comment by rumplin** [comment]
Sorry, I have tried so many projects I didn't even look at when it was last changed. You can ignore this ticked if the project is discontinued.
